/**:
  ros__parameters:
    # Motion parameters
    forward_speed: 0.2
    rotation_speed: 0.5  # rad/s
    min_forward_duration : 5.0
    max_forward_duration : 5.0

    # Sweep behavior parameters
    sweep_range_deg: 60.0
    sweep_increment_deg: 10.0
    sweep_wait_duration: 4.0  # seconds

    # Threshold parameters
    threshold_drive: 20.0
    threshold_goal: 500.0